export const BUSINESS_SECTIONS = {
  LUXE: "LUXE",
  ESSENTIAL: "ESSENTIAL",
};

export const BUSINESS_SECTION_LABELS = {
  [BUSINESS_SECTIONS.LUXE]: "EMBER & CO. LUXE",
  [BUSINESS_SECTIONS.ESSENTIAL]: "EMBER & CO. ESSENTIAL",
};

export const QUOTATION_STATUSES = {
  DRAFT: "DRAFT",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED: "APPROVED",
  SENT: "SENT",
  CANCELLED: "CANCELLED",
};

export const QUOTATION_STATUS_LABELS = {
  [QUOTATION_STATUSES.DRAFT]: "Draft",
  [QUOTATION_STATUSES.PENDING_APPROVAL]: "Pending Approval",
  [QUOTATION_STATUSES.APPROVED]: "Approved",
  [QUOTATION_STATUSES.SENT]: "Sent",
  [QUOTATION_STATUSES.CANCELLED]: "Cancelled",
};

export const APPROVAL_STATUSES = {
  NOT_REQUIRED: "NOT_REQUIRED",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const APPROVAL_STATUS_LABELS = {
  [APPROVAL_STATUSES.NOT_REQUIRED]: "Not Required",
  [APPROVAL_STATUSES.PENDING]: "Pending",
  [APPROVAL_STATUSES.APPROVED]: "Approved",
  [APPROVAL_STATUSES.REJECTED]: "Rejected",
};

export const PRODUCT_CATEGORY_CODES = {
  SMALL_MAKEUP: "SMALL_MAKEUP",
  LIP_PRODUCTS: "LIP_PRODUCTS",
  FOUNDATION: "FOUNDATION",
  SMALL_EYESHADOW_PALETTE: "SMALL_EYESHADOW_PALETTE",
  LARGE_EYESHADOW_PALETTE: "LARGE_EYESHADOW_PALETTE",
  MINI_SKINCARE: "MINI_SKINCARE",
  REGULAR_SKINCARE: "REGULAR_SKINCARE",
  MINI_HAIRCARE: "MINI_HAIRCARE",
  REGULAR_HAIRCARE: "REGULAR_HAIRCARE",
  PERFUME: "PERFUME",
  DAILY_ESSENTIALS: "DAILY_ESSENTIALS",
  ELECTRONICS: "ELECTRONICS",
  SUPPLEMENTS: "SUPPLEMENTS",
};

export const PRICING_TYPES = {
  FIXED: "FIXED",
  PERCENTAGE: "PERCENTAGE",
  PRICE_THRESHOLD: "PRICE_THRESHOLD",
};

export const SHIPPING_METHOD_CODES = {
  AIR_CARGO: "AIR_CARGO",
  EXPRESS: "EXPRESS",
};

export const CURRENT_USER = {
  name: "Ember Team",
  role: "Pricing Specialist",
};

export const SUPPLEMENT_CONFIRMATION_WARNING =
  "Supplement pricing requires confirmation from management.";

export const SPECIAL_REQUEST_APPROVAL_WARNING =
  "Special requests require management approval before a quotation can be approved or sent.";
